name: Release Docker image for the app

on:
  pull_request:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and push
      uses: byzanteam/jet-actions/fe-build-image@chore/yangke/package-ali-github
      with:
        registries: |-
          registry.cn-chengdu.aliyuncs.com,yk-tools,${{ secrets.ALIYUN_ID }},${{ secrets.ALIYUN_KEY }}
          ghcr.io,ykelit,${{ github.repository_owner }},${{ secrets.HUB_KEY }}
        dockerfile: ./Dockerfile
