name: Release Docker image for the app

on:
  pull_request:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
     -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          khronosy/go-ide
          registry.cn-chengdu.aliyuncs.com/yk-tools/go-ide
          ghcr.io/ykelit/go-ide            
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha  
    -
      name: Login to Docker HUb
      uses: docker/login-action@v2
      with:
        username: khronosy
        password: ${{ secrets.DOCKER_KEY }}
    -
      name: Login to aliyun registry
      uses: docker/login-action@v2
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.ALIYUN_ID }}
        password: ${{ secrets.ALIYUN_KEY }}
    -
      name: Login to github registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.HUB_KEY }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

